### ISSUE TITLE
Add a font sample

### ISSUE THREAD

**Issue by kw217** [fontfish/ProtoMinchoKana#2]
Hi @fontfish - this project looks really interesting! However it would be great to see what the font actually looks like. Could you add a PNG sample, or a webfont-based preview?

**Comment by fontfish** [comment]
Hello, @kw217 
Thanks for the interest and advice, and apologies for the wait. I've finally added a basic sample PNG. A webfont sample would be nice but will probably have to wait until everything's more complete and I have the time to figure out how.

**Comment by kw217** [comment]
Awesome, thanks!
